# Generated by Django 5.0.2 on 2024-02-12 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_securekeys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='securekeys',
            name='s_key',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
