# Generated by Django 5.0.2 on 2024-02-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_securekeys_s_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saved_password',
            name='password',
            field=models.BinaryField(),
        ),
    ]
